# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hubless}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Greg Sterndale"]
  s.date = %q{2010-01-17}
  s.default_executable = %q{hubless}
  s.description = %q{Search your local gem repository for gems installed from GitHub that have since moved to Gemcutter}
  s.email = %q{greg@plectix.com}
  s.executables = ["hubless"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/hubless",
     "hubless.gemspec",
     "lib/application.rb",
     "lib/gem_description.rb",
     "lib/hubless.rb",
     "test/helper.rb",
     "test/test_application.rb",
     "test/test_gem_description.rb",
     "test/test_hubless.rb"
  ]
  s.homepage = %q{http://github.com/gsterndale/hubless}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Search your local gem repository for gems installed from GitHub that have since moved to Gemcutter}
  s.test_files = [
    "test/helper.rb",
     "test/test_application.rb",
     "test/test_gem_description.rb",
     "test/test_hubless.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<mocha>, [">= 0.9.1"])
    else
      s.add_dependency(%q<mocha>, [">= 0.9.1"])
    end
  else
    s.add_dependency(%q<mocha>, [">= 0.9.1"])
  end
end

